[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "deep-translator>=1.11.4",
    "discord-py>=2.5.2",
    "google-genai>=1.24.0",
    "python-dotenv>=1.1.1",
]
